package exceptions.practice;

public class ExceptionDemo {

	public static void main(String args[]) throws ArrayIndexOutOfBoundsException {
		
		String str = new String();
		System.out.println(str.charAt(0));
		 
		
	} 
} 
/*try {
//Protected code
} catch (ExceptionName e1) {
//Catch block
}*/
